version: "3"
services:
 redis:
  image: redis
  deploy:
   replicas: 1
   resources:
    cpus: "0.1"
    memory: 256M
   restart_policy:
    condition: on-failure
  networks:
   - opnet
 webauth:
  context: ./webauth
  image: webauth
  deploy:
   replicas: 1
   resources:
    cpus: "0.1"
    memory: 256M
   restart_policy:
    condition: on-failure
  links:
   - redis
  command:
   java -jar webauth-1.0-jar-with-dependencies.jar
networks:
 opnet:

