version: "3"
services:
 redis:
  image: redis
  deploy:
   replicas: 1
   resources:
    cpus: "0.1"
    memory: 256M
   restart_policy:
    condition: on-failure
  expose:
   - "6379"
  networks:
   - opnet
 pgsql:
  build: ./db
  image: hur/pgsql:9.6.3
  deploy:
   replicas: 1
   resources:
    cpus: "0.3"
    memory: 512M
   restart_policy:
    condition: on-failure
  environment:
   POSTGRES_PASSWORD: faisal123
  networks:
   - opnet
 webauth:
  build: ./webauth
  image: hur/webauth:1.0.0-alpha
  deploy:
   replicas: 1
   resources:
    cpus: "0.1"
    memory: 256M
   restart_policy:
    condition: on-failure
  links:
   - redis
   - pgsql
  environment:
   REDIS_SERVER: redis
   MQ_HOST: rabbitmq
   MQ_USERNAME: svc
   MQ_PASSWORD: svc
   DB_HOST: pgsql
   DB_USERNAME: postgres
   DB_PASSWORD: faisal123
  depends_on:
   - redis
   - pgsql
  expose:
   - "80"
  networks:
   - opnet
 rabbitmq:
  build: ./rabbitmq
  image: hur/rabbitmq:3.6.8-management
  deploy:
   replicas: 1
   resources:
    cpus: "0.3"
    memory: 512M
   restart_policy:
    condition: on-failure
  links:
   - webauth
  depends_on:
   - webauth
  ports:
   - "15672:15672"
  expose:
   - "5672"
  networks:
   - opnet
 fxyahoo:
  build: ./fxyahoo
  image: hur/fxyahoo:1.0.0-alpha
  deploy:
   replicas: 1
   resources:
    cpus: "0.1"
    memory: 128M
   restart_policy:
    condition: on-failure
  links:
   - redis
   - pgsql
   - rabbitmq
  environment:
   REDIS_SERVER: redis
   MQ_HOST: rabbitmq
   MQ_USERNAME: svc
   MQ_PASSWORD: svc
   DB_HOST: pgsql
   DB_USERNAME: postgres
   DB_PASSWORD: faisal123
  depends_on:
   - redis
   - pgsql
   - rabbitmq
  networks:
   - opnet
 mqstats:
  build: ./mqstats
  image: hur/mqstats:1.0.0-alpha
  deploy:
   replicas: 1
   resources:
    cpus: "0.1"
    memory: 128M
   restart_policy:
    condition: on-failure
  links:
   - redis
   - pgsql
   - rabbitmq
  environment:
   REDIS_SERVER: redis
   MQ_HOST: rabbitmq
   MQ_USERNAME: svc
   MQ_PASSWORD: svc
   DB_HOST: pgsql
   DB_USERNAME: postgres
   DB_PASSWORD: faisal123
  depends_on:
   - redis
   - pgsql
   - rabbitmq
  networks:
   - opnet
networks:
 opnet: